import { useEffect, useState } from 'react';
import api from '../api/client';
import { toast } from '../components/Toaster';

export default function Security() {
  const [qrCode, setQrCode] = useState('');
  const [code, setCode] = useState('');
  const [busy, setBusy] = useState(false);
  const [enabled, setEnabled] = useState(false);

  useEffect(() => {
    // Setup MFA if not already enabled
    api.get('/auth/mfa/setup/')
      .then(res => {
        setQrCode(res.data.qr_code);
      })
      .catch(() => toast.error('Could not fetch MFA details.'));
  }, []);

  const verifyMfa = async (e) => {
    e.preventDefault();
    setBusy(true);
    try {
      await api.post('/auth/mfa/verify/', { code });
      setEnabled(true);
      toast.success('MFA successfully enabled!');
    } catch (err) {
      toast.error('Invalid code. Please try again.');
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="max-w-md mx-auto">
      <header className="mb-8">
        <h1 className="font-serif-display text-3xl font-bold text-on-surface mb-2">Security</h1>
        <p className="text-on-surface-variant text-sm">
          Set up Multi-Factor Authentication (MFA) to secure your caregiver account.
        </p>
      </header>

      <div className="vb-card">
        {enabled ? (
          <div className="text-center py-8 text-secondary">
            <span className="material-symbols-outlined text-5xl mb-4">gpp_good</span>
            <h2 className="text-xl font-bold text-on-surface">MFA is Active</h2>
            <p className="text-sm text-on-surface-variant mt-2">Your account is secured with multi-factor authentication.</p>
          </div>
        ) : (
          <>
            <h3 className="text-lg font-bold text-on-surface mb-4">Enable MFA</h3>
            <p className="text-sm text-on-surface-variant mb-4">
              1. Scan this QR code with your authenticator app (like Google Authenticator or Authy).
            </p>
            {qrCode && (
              <div className="bg-white p-4 rounded-xl inline-block mb-4 border border-outline-variant">
                <img src={`data:image/png;base64,${qrCode}`} alt="MFA QR Code" className="w-48 h-48" />
              </div>
            )}
            <p className="text-sm text-on-surface-variant mb-4">
              2. Enter the 6-digit code generated by the app to verify.
            </p>
            <form onSubmit={verifyMfa} className="flex gap-2">
              <input
                type="text"
                className="vb-input flex-1"
                placeholder="000000"
                maxLength="6"
                required
                value={code}
                onChange={e => setCode(e.target.value)}
              />
              <button type="submit" disabled={busy || code.length !== 6} className="vb-btn-primary">
                {busy ? 'Verifying...' : 'Verify'}
              </button>
            </form>
          </>
        )}
      </div>
    </div>
  );
}
