# Copyright (c) 2026 Afsara Saima Mannan
# Licensed under the PolyForm Noncommercial License 1.0. 
# See the LICENSE.txt file in the project root for full terms.

# Generated by Django 4.2.11 on 2026-05-13 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('device_model', models.CharField(blank=True, max_length=120)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_status', to='accounts.child')),
            ],
            options={
                'ordering': ['-last_synced_at'],
            },
        ),
    ]
