# Generated by Django 4.2.11 on 2026-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_carenote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='carenote',
            new_name='accounts_ca_caregiv_292bd0_idx',
            old_name='accounts_ca_caregiv_idx',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
