# Generated by Django 4.2.11 on 2026-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_medication_dailylog_medicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
