# Generated by Django 4.2.11 on 2026-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_caregiver_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='caregiver_avatars/%Y/%m/'),
        ),
    ]
