# Generated by Django 4.2.11 on 2026-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_caregiver_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='carenote',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
