/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-background": "#1e1b1b",
              "secondary": "#37656b",
              "error": "#ba1a1a",
              "secondary-fixed": "#bbebf1",
              "tertiary": "#3d6922",
              "inverse-primary": "#e7bbc6",
              "outline-variant": "#d3c3c5",
              "primary": "#78555e",
              "surface-bright": "#fff8f8",
              "on-surface-variant": "#4f4446",
              "inverse-surface": "#332f30",
              "primary-fixed-dim": "#e7bbc6",
              "tertiary-fixed-dim": "#a2d580",
              "on-secondary-fixed-variant": "#1d4d53",
              "outline": "#817476",
              "on-tertiary-container": "#406c24",
              "tertiary-fixed": "#bdf199",
              "on-primary-fixed-variant": "#5e3e47",
              "surface-container-lowest": "#ffffff",
              "surface-container": "#f4ecec",
              "on-secondary-container": "#3b6a6f",
              "on-primary-container": "#7a5761",
              "secondary-container": "#b8e8ee",
              "on-surface": "#1e1b1b",
              "surface-tint": "#78555e",
              "on-secondary": "#ffffff",
              "secondary-fixed-dim": "#9fcfd5",
              "primary-container": "#ffd1dc",
              "surface-container-low": "#faf2f2",
              "tertiary-container": "#b8ec94",
              "surface-variant": "#e9e0e1",
              "error-container": "#ffdad6",
              "surface-container-high": "#efe6e7",
              "on-tertiary-fixed-variant": "#26500a",
              "on-secondary-fixed": "#001f23",
              "surface-dim": "#e0d8d8",
              "surface": "#fff8f8",
              "background": "#fff8f8",
              "surface-container-highest": "#e9e0e1",
              "on-primary": "#ffffff",
              "inverse-on-surface": "#f7efef",
              "on-primary-fixed": "#2d141c",
              "on-error": "#ffffff",
              "on-tertiary-fixed": "#092100",
              "on-tertiary": "#ffffff",
              "primary-fixed": "#ffd9e2",
              "on-error-container": "#93000a"
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "spacing": {
              "md": "24px",
              "base": "8px",
              "gutter": "24px",
              "lg": "48px",
              "sm": "12px",
              "xl": "80px",
              "xs": "4px",
              "container-margin": "32px"
      },
      "fontFamily": {
              "headline-lg": ["Noto Serif", "serif"],
              "body-sm": ["Public Sans", "sans-serif"],
              "display-lg": ["Noto Serif", "serif"],
              "headline-lg-mobile": ["Noto Serif", "serif"],
              "title-md": ["Public Sans", "sans-serif"],
              "body-lg": ["Public Sans", "sans-serif"],
              "label-caps": ["Public Sans", "sans-serif"],
              "public-sans": ["Public Sans", "sans-serif"],
              "sans": ["Public Sans", "sans-serif"]
      },
      "fontSize": {
              "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "500"}],
              "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "400"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
              "title-md": ["18px", {"lineHeight": "1.5", "fontWeight": "600"}],
              "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
};
