# Generated by Django 4.2.11 on 2026-05-13 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('scenario', models.CharField(db_index=True, help_text="e.g. 'Mealtime', 'School Day', 'Doctor visit', 'Emergency'", max_length=40)),
                ('language', models.CharField(db_index=True, default='en', max_length=10)),
                ('layout', models.JSONField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='templates/covers/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-download_count', '-created_at'],
                'indexes': [models.Index(fields=['status', 'scenario'], name='community_t_status_713b95_idx'), models.Index(fields=['language'], name='community_t_languag_f0ef97_idx')],
            },
        ),
    ]
