# Copyright (c) 2026 Afsara Saima Mannan
# Licensed under the PolyForm Noncommercial License 1.0. 
# See the LICENSE.txt file in the project root for full terms.

# Generated by Django 4.2.11 on 2026-05-13 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('icons', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_events', to='accounts.child')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tap_events', to='icons.icon')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['child', 'timestamp'], name='analytics_t_child_i_a4cd96_idx')],
            },
        ),
    ]
