# Copyright (c) 2026 Afsara Saima Mannan
# Licensed under the PolyForm Noncommercial License 1.0. 
# See the LICENSE.txt file in the project root for full terms.

# Generated by Django 4.2.11 on 2026-05-20 12:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import icons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Short caption shown beside the icon, e.g. 'Water'.", max_length=80)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Drink'), ('EMOTIONS', 'Emotions'), ('BODY', 'Body & Hygiene'), ('ACTIVITIES', 'Activities'), ('PEOPLE', 'People'), ('PLACES', 'Places'), ('REQUESTS', 'Requests & Needs'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=16)),
                ('image', models.ImageField(upload_to='icons/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp']), icons.models.validate_image])),
                ('audio', models.FileField(help_text='The voice the child will hear when tapping this icon.', upload_to='icons/audio/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a', 'ogg']), icons.models.validate_audio])),
                ('tts_text', models.CharField(blank=True, help_text='Text-to-speech fallback text used by the Android app.', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'label'],
                'indexes': [models.Index(fields=['owner', 'category'], name='icons_icon_owner_i_555182_idx'), models.Index(fields=['updated_at'], name='icons_icon_updated_347c44_idx')],
            },
        ),
    ]
