# Generated by Django 4.2.11 on 2026-06-19 16:21

import django.core.validators
from django.db import migrations, models
import icons.models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='audio',
            field=models.FileField(help_text='The voice the child will hear when tapping this icon.', upload_to='icons/audio/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a', 'ogg', 'webm', 'weba']), icons.models.validate_audio]),
        ),
        migrations.AlterField(
            model_name='icon',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food & Drink'), ('EMOTIONS', 'Emotions'), ('BODY', 'Body & Hygiene'), ('ACTIVITIES', 'Activities'), ('PEOPLE', 'People'), ('PLACES', 'Places'), ('REQUESTS', 'Requests & Needs'), ('EMERGENCY', 'Emergency'), ('ROUTINES', 'Routines'), ('MEDICATIONS', 'Medications'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=16),
        ),
    ]
