# Generated by Django 4.2.11 on 2026-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0002_alter_icon_audio_alter_icon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='icon',
            name='language',
            field=models.CharField(blank=True, default='English', help_text='e.g. English, Bengali, Spanish', max_length=40),
        ),
    ]
