# Generated by Django 4.2.11 on 2026-06-30 15:54

import django.core.validators
from django.db import migrations, models
import icons.models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0003_icon_is_shared_icon_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='audio',
            field=models.FileField(blank=True, help_text='The voice the child will hear when tapping this icon.', null=True, upload_to='icons/audio/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a', 'ogg', 'webm', 'weba']), icons.models.validate_audio]),
        ),
    ]
