# Generated by Django 4.2.11 on 2026-06-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0004_alter_icon_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='is_folder_dp',
            field=models.BooleanField(default=False, help_text='If true, this icon only shows in the Folder DP library.'),
        ),
    ]
