# Generated by Django 4.2.11 on 2026-06-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0005_icon_is_folder_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='arasaac_id',
            field=models.CharField(blank=True, help_text='If imported from ARASAAC, the original ID.', max_length=50, null=True),
        ),
    ]
