# Generated by Django 4.2.11 on 2026-06-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0006_icon_arasaac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='category',
            field=models.CharField(choices=[('EAT', 'To eat'), ('DRINK', 'To drink'), ('EMOTIONS', 'Emotions'), ('BODY', 'Body & Hygiene'), ('ACTIVITIES', 'Activities'), ('PEOPLE', 'People'), ('PLACES', 'Places'), ('REQUESTS', 'Requests & Needs'), ('EMERGENCY', 'Emergency'), ('ROUTINES', 'Routines'), ('MEDICATIONS', 'Medications'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=16),
        ),
    ]
