# Generated by Django 4.2.11 on 2026-06-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0009_alter_icon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food & Drink'), ('EMOTIONS', 'Emotions'), ('BODY', 'Body & Hygiene'), ('ACTIVITIES', 'Activities'), ('PEOPLE', 'People'), ('PLACES', 'Places'), ('REQUESTS', 'Requests & Needs'), ('EMERGENCY', 'Emergency'), ('ROUTINES', 'Routines'), ('MEDICATIONS', 'Medications'), ('ANIMALS', 'Animals & Pets'), ('CLOTHING', 'Clothing & Accessories'), ('TOYS', 'Toys & Games'), ('SCHOOL', 'School & Education'), ('COLORS', 'Colors'), ('SHAPES', 'Shapes'), ('NUMBERS', 'Numbers & Math'), ('TIME', 'Time & Days'), ('WEATHER', 'Weather & Seasons'), ('TRANSPORT', 'Transportation'), ('NATURE', 'Nature & Outdoors'), ('HOME', 'Home & Furniture'), ('KITCHEN', 'Kitchen & Cooking'), ('BATHROOM', 'Bathroom Items'), ('BEDROOM', 'Bedroom Items'), ('ELECTRONICS', 'Electronics & Tech'), ('SPORTS', 'Sports & Fitness'), ('MUSIC', 'Music & Instruments'), ('ART', 'Art & Craft'), ('PROFESSIONS', 'Jobs & Professions'), ('HOLIDAYS', 'Holidays & Events'), ('CHORES', 'Chores & Tasks'), ('SENSORY', 'Sensory Needs'), ('SOCIAL', 'Social Greetings'), ('QUESTIONS', 'Questions'), ('DESCRIPTIONS', 'Adjectives & Descriptions'), ('ACTIONS', 'Actions & Verbs'), ('PREPOSITIONS', 'Positions & Directions'), ('PRONOUNS', 'Pronouns'), ('FEELINGS', 'Physical Feelings'), ('MEDICAL', 'Medical & Doctor'), ('THERAPY', 'Therapy & Exercises'), ('HOBBIES', 'Hobbies & Interests'), ('MEDIA', 'TV, Movies & Books'), ('SNACKS', 'Snacks & Treats'), ('DRINKS', 'Drinks & Beverages'), ('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('DESSERTS', 'Desserts & Sweets'), ('UTENSILS', 'Utensils'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=16),
        ),
    ]
