# Generated by Django 4.2.11 on 2026-05-13 09:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('icons', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('rows', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cols', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Hex colour for the canvas background.', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive boards are not synced to the child's device.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, help_text='Which child this board is for. Optional for shared templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='accounts.child')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('col', models.PositiveSmallIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boards.board')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='icons.icon')),
            ],
            options={
                'ordering': ['row', 'col'],
            },
        ),
        migrations.AddField(
            model_name='board',
            name='icons',
            field=models.ManyToManyField(related_name='boards', through='boards.BoardItem', to='icons.icon'),
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='boarditem',
            index=models.Index(fields=['board', 'row', 'col'], name='boards_boar_board_i_1bbbf5_idx'),
        ),
        migrations.AddConstraint(
            model_name='boarditem',
            constraint=models.UniqueConstraint(fields=('board', 'row', 'col'), name='unique_cell_per_board'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['owner', 'is_active'], name='boards_boar_owner_i_ae72b5_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['child'], name='boards_boar_child_i_816bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['updated_at'], name='boards_boar_updated_34c39d_idx'),
        ),
    ]
