# Copyright (c) 2026 Afsara Saima Mannan
# Licensed under the PolyForm Noncommercial License 1.0. 
# See the LICENSE.txt file in the project root for full terms.

# Generated by Django 4.2.11 on 2026-05-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_boardversion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='boardversion',
            new_name='boards_boar_board_i_01009b_idx',
            old_name='boards_boa_board_i_idx',
        ),
    ]
