# Generated by Django 4.2.11 on 2026-06-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0004_alter_icon_audio'),
        ('boards', '0003_rename_boards_boa_board_i_idx_boards_boar_board_i_01009b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cover_icon',
            field=models.ForeignKey(blank=True, help_text='The DP / Cover image shown on the outside of the folder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='icons.icon'),
        ),
    ]
