# Generated by Django 4.2.11 on 2026-06-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0005_icon_is_folder_dp'),
        ('boards', '0004_board_cover_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarditem',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='icons.icon'),
        ),
    ]
