# Generated by Django 4.2.11 on 2026-06-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_boarditem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If this board sits inside another folder/board.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_boards', to='boards.board'),
        ),
    ]
